name: Build and Release

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: Get version
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/alist-org/alist/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lmq8267/alist/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build
        run: |
          rm -rf /opt/st
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          git clone https://github.com/lmq8267/cloudflared.git /opt/ali
          cd /opt/ali
          sudo chmod 0777 /etc/resolv.conf
          cat >>/etc/resolv.conf <<EOF
          nameserver 8.8.8.8 
          nameserver 4.4.4.4
          EOF
          #curl -o "alist-linux-musl-mipsle.tar.gz" "https://github.com/alist-org/alist/releases/download/${{tag}}/alist-linux-musl-mipsle.tar.gz" 
          #tar -xzvf alist-linux-musl-mipsle.tar.gz -C /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          chmod 777 /opt/ali/up.sh
          /opt/ali/up.sh
          cd /opt/st
          /opt/st/strip alist
          /opt/upx-3.95-amd64_linux/upx --lzma --best alist
          tar czvf alist.tar.gz alist
          echo $(md5sum alist.tar.gz | awk '{print $1;}') >MD5.txt
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/st/alist.tar.gz
              /opt/st/alist
              /opt/st/MD5.txt
     
